#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = uint32_t;//__uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfbdb;
constexpr uint24_t FX_DATA_BYTES = 267381;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Images
{
  constexpr uint24_t Fire = 0x000000;
  constexpr uint16_t FireWidth  = 64;
  constexpr uint16_t FireHeight = 64;
  constexpr uint8_t  FireFrames = 16;

  constexpr uint24_t Title_Text = 0x002004;
  constexpr uint16_t Title_Text_width  = 57;
  constexpr uint16_t Title_Text_height = 64;

  constexpr uint24_t Title_Options = 0x002398;
  constexpr uint16_t Title_Options_width  = 17;
  constexpr uint16_t Title_Options_height = 64;

  constexpr uint24_t Skull_Large = 0x0024AC;
  constexpr uint16_t Skull_Large_width  = 52;
  constexpr uint16_t Skull_Large_height = 40;
  constexpr uint8_t  Skull_Large_frames = 4;

  constexpr uint24_t Skull_Eyes = 0x0028C0;
  constexpr uint16_t Skull_Eyes_width  = 10;
  constexpr uint16_t Skull_Eyes_height = 24;
  constexpr uint8_t  Skull_Eyes_frames = 48;

  constexpr uint24_t LevelEntry = 0x002E64;
  constexpr uint16_t LevelEntryWidth  = 70;
  constexpr uint16_t LevelEntryHeight = 64;

  constexpr uint24_t Dice_Roll = 0x0032C8;
  constexpr uint16_t Dice_Roll_width  = 12;
  constexpr uint16_t Dice_Roll_height = 16;
  constexpr uint8_t  Dice_Roll_frames = 9;

  constexpr uint24_t Dice_Black = 0x0033A4;
  constexpr uint16_t Dice_Black_width  = 12;
  constexpr uint16_t Dice_Black_height = 16;
  constexpr uint8_t  Dice_Black_frames = 7;

  constexpr uint24_t Dice_Fade = 0x003450;
  constexpr uint16_t Dice_Fade_width  = 12;
  constexpr uint16_t Dice_Fade_height = 16;
  constexpr uint8_t  Dice_Fade_frames = 60;

  constexpr uint24_t Background_00 = 0x0039F4;
  constexpr uint16_t Background_00_width  = 57;
  constexpr uint16_t Background_00_height = 64;

  constexpr uint24_t Background_02 = 0x003BC0;
  constexpr uint16_t Background_02_width  = 15;
  constexpr uint16_t Background_02_height = 64;

  constexpr uint24_t Button_PlayHand = 0x003C3C;
  constexpr uint16_t Button_PlayHand_width  = 24;
  constexpr uint16_t Button_PlayHand_height = 24;

  constexpr uint24_t Button_Reroll = 0x003C88;
  constexpr uint16_t Button_Reroll_width  = 24;
  constexpr uint16_t Button_Reroll_height = 24;

  constexpr uint24_t Swap = 0x003CD4;
  constexpr uint16_t SwapWidth  = 13;
  constexpr uint16_t SwapHeight = 64;

  constexpr uint24_t GameOver = 0x003D40;
  constexpr uint16_t GameOverWidth  = 128;
  constexpr uint16_t GameOverHeight = 64;

  constexpr uint24_t GameWin = 0x004544;
  constexpr uint16_t GameWinWidth  = 128;
  constexpr uint16_t GameWinHeight = 64;

  constexpr uint24_t Bones_Heading = 0x004D48;
  constexpr uint16_t Bones_Heading_width  = 14;
  constexpr uint16_t Bones_Heading_height = 32;

  constexpr uint24_t Hand_Names = 0x004D84;
  constexpr uint16_t Hand_Names_width  = 6;
  constexpr uint16_t Hand_Names_height = 36;
  constexpr uint8_t  Hand_Names_frames = 9;

  constexpr uint24_t Upgrade = 0x004E96;
  constexpr uint16_t UpgradeWidth  = 5;
  constexpr uint16_t UpgradeHeight = 32;

  constexpr uint24_t Total = 0x004EAE;
  constexpr uint16_t TotalWidth  = 5;
  constexpr uint16_t TotalHeight = 24;

  constexpr uint24_t Multiplier = 0x004EC1;
  constexpr uint16_t MultiplierWidth  = 5;
  constexpr uint16_t MultiplierHeight = 40;

  constexpr uint24_t Speech_Sml = 0x004EDE;
  constexpr uint16_t Speech_Sml_width  = 8;
  constexpr uint16_t Speech_Sml_height = 64;
  constexpr uint8_t  Speech_Sml_frames = 12;

  constexpr uint24_t Speech_Lrg = 0x0051E2;
  constexpr uint16_t Speech_Lrg_width  = 33;
  constexpr uint16_t Speech_Lrg_height = 64;
  constexpr uint8_t  Speech_Lrg_frames = 10;

  constexpr uint24_t SkullInfo_Top = 0x005C36;
  constexpr uint16_t SkullInfo_Top_width  = 16;
  constexpr uint16_t SkullInfo_Top_height = 64;

  constexpr uint24_t SkullInfo_Bot = 0x005CBA;
  constexpr uint16_t SkullInfo_Bot_width  = 16;
  constexpr uint16_t SkullInfo_Bot_height = 64;

  constexpr uint24_t HandScore_Top = 0x005D3E;
  constexpr uint16_t HandScore_Top_width  = 48;
  constexpr uint16_t HandScore_Top_height = 64;
  constexpr uint8_t  HandScore_Top_frames = 4;

  constexpr uint24_t HandScore_Bot = 0x006342;
  constexpr uint16_t HandScore_Bot_width  = 15;
  constexpr uint16_t HandScore_Bot_height = 64;
  constexpr uint8_t  HandScore_Bot_frames = 4;

  constexpr uint24_t Skeleton_Hand = 0x006526;
  constexpr uint16_t Skeleton_Hand_width  = 18;
  constexpr uint16_t Skeleton_Hand_height = 16;

  constexpr uint24_t Inventory_Top = 0x006572;
  constexpr uint16_t Inventory_Top_width  = 32;
  constexpr uint16_t Inventory_Top_height = 64;

  constexpr uint24_t Inventory_Bot = 0x006676;
  constexpr uint16_t Inventory_Bot_width  = 13;
  constexpr uint16_t Inventory_Bot_height = 64;
  constexpr uint8_t  Inventory_Bot_frames = 5;

  constexpr uint24_t UpgradeHand_Top = 0x006882;
  constexpr uint16_t UpgradeHand_Top_width  = 13;
  constexpr uint16_t UpgradeHand_Top_height = 64;

  constexpr uint24_t UpgradeHand_Bot = 0x0068EE;
  constexpr uint16_t UpgradeHand_Bot_width  = 15;
  constexpr uint16_t UpgradeHand_Bot_height = 64;
  constexpr uint8_t  UpgradeHand_Bot_frames = 3;

  constexpr uint24_t UpgradeHands = 0x006A5A;
  constexpr uint16_t UpgradeHandsWidth  = 24;
  constexpr uint16_t UpgradeHandsHeight = 64;
  constexpr uint8_t  UpgradeHandsFrames = 24;

  constexpr uint24_t UpgradeHand_Cursor = 0x007C5E;
  constexpr uint16_t UpgradeHand_Cursor_width  = 33;
  constexpr uint16_t UpgradeHand_Cursor_height = 64;

  constexpr uint24_t SkullSelect_Top = 0x007D6A;
  constexpr uint16_t SkullSelect_Top_width  = 13;
  constexpr uint16_t SkullSelect_Top_height = 64;

  constexpr uint24_t SkullSelect_Bot = 0x007DD6;
  constexpr uint16_t SkullSelect_Bot_width  = 13;
  constexpr uint16_t SkullSelect_Bot_height = 64;

  constexpr uint24_t Skull_Names = 0x007E42;
  constexpr uint16_t Skull_Names_width  = 6;
  constexpr uint16_t Skull_Names_height = 41;
  constexpr uint8_t  Skull_Names_frames = 20;

  constexpr uint24_t Skull_Cursor = 0x008116;
  constexpr uint16_t Skull_Cursor_width  = 48;
  constexpr uint16_t Skull_Cursor_height = 64;

  constexpr uint24_t Skull_00 = 0x00829A;
  constexpr uint16_t Skull_00_width  = 48;
  constexpr uint16_t Skull_00_height = 64;

  constexpr uint24_t Skull_01 = 0x00841E;
  constexpr uint16_t Skull_01_width  = 48;
  constexpr uint16_t Skull_01_height = 64;

  constexpr uint24_t Skull_02 = 0x0085A2;
  constexpr uint16_t Skull_02_width  = 48;
  constexpr uint16_t Skull_02_height = 64;

  constexpr uint24_t Skull_03 = 0x008726;
  constexpr uint16_t Skull_03_width  = 48;
  constexpr uint16_t Skull_03_height = 64;

  constexpr uint24_t Skull_04 = 0x0088AA;
  constexpr uint16_t Skull_04_width  = 48;
  constexpr uint16_t Skull_04_height = 64;

  constexpr uint24_t Skull_05 = 0x008A2E;
  constexpr uint16_t Skull_05_width  = 48;
  constexpr uint16_t Skull_05_height = 64;

  constexpr uint24_t Skull_06 = 0x008BB2;
  constexpr uint16_t Skull_06_width  = 48;
  constexpr uint16_t Skull_06_height = 64;

  constexpr uint24_t Skull_07 = 0x008D36;
  constexpr uint16_t Skull_07_width  = 48;
  constexpr uint16_t Skull_07_height = 64;

  constexpr uint24_t Skull_08 = 0x008EBA;
  constexpr uint16_t Skull_08_width  = 48;
  constexpr uint16_t Skull_08_height = 64;

  constexpr uint24_t Skull_09 = 0x00903E;
  constexpr uint16_t Skull_09_width  = 48;
  constexpr uint16_t Skull_09_height = 64;

  constexpr uint24_t Skull_10 = 0x0091C2;
  constexpr uint16_t Skull_10_width  = 48;
  constexpr uint16_t Skull_10_height = 64;

  constexpr uint24_t Skull_11 = 0x009346;
  constexpr uint16_t Skull_11_width  = 48;
  constexpr uint16_t Skull_11_height = 64;

  constexpr uint24_t Skull_12 = 0x0094CA;
  constexpr uint16_t Skull_12_width  = 48;
  constexpr uint16_t Skull_12_height = 64;

  constexpr uint24_t Skull_13 = 0x00964E;
  constexpr uint16_t Skull_13_width  = 48;
  constexpr uint16_t Skull_13_height = 64;

  constexpr uint24_t Skull_14 = 0x0097D2;
  constexpr uint16_t Skull_14_width  = 48;
  constexpr uint16_t Skull_14_height = 64;

  constexpr uint24_t Skull_15 = 0x009956;
  constexpr uint16_t Skull_15_width  = 48;
  constexpr uint16_t Skull_15_height = 64;

  constexpr uint24_t Skull_16 = 0x009ADA;
  constexpr uint16_t Skull_16_width  = 48;
  constexpr uint16_t Skull_16_height = 64;

  constexpr uint24_t Skull_17 = 0x009C5E;
  constexpr uint16_t Skull_17_width  = 48;
  constexpr uint16_t Skull_17_height = 64;

  constexpr uint24_t Skull_18 = 0x009DE2;
  constexpr uint16_t Skull_18_width  = 48;
  constexpr uint16_t Skull_18_height = 64;

  constexpr uint24_t Skull_19 = 0x009F66;
  constexpr uint16_t Skull_19_width  = 48;
  constexpr uint16_t Skull_19_height = 64;

  constexpr uint24_t Skull_Thumb_00 = 0x00A0EA;
  constexpr uint16_t Skull_Thumb_00_width  = 23;
  constexpr uint16_t Skull_Thumb_00_height = 64;

  constexpr uint24_t Skull_Thumb_01 = 0x00A1A6;
  constexpr uint16_t Skull_Thumb_01_width  = 23;
  constexpr uint16_t Skull_Thumb_01_height = 64;

  constexpr uint24_t Skull_Thumb_02 = 0x00A262;
  constexpr uint16_t Skull_Thumb_02_width  = 23;
  constexpr uint16_t Skull_Thumb_02_height = 64;

  constexpr uint24_t Skull_Thumb_03 = 0x00A31E;
  constexpr uint16_t Skull_Thumb_03_width  = 23;
  constexpr uint16_t Skull_Thumb_03_height = 64;

  constexpr uint24_t Skull_Thumb_04 = 0x00A3DA;
  constexpr uint16_t Skull_Thumb_04_width  = 23;
  constexpr uint16_t Skull_Thumb_04_height = 64;

  constexpr uint24_t Skull_Thumb_05 = 0x00A496;
  constexpr uint16_t Skull_Thumb_05_width  = 23;
  constexpr uint16_t Skull_Thumb_05_height = 64;

  constexpr uint24_t Skull_Thumb_06 = 0x00A552;
  constexpr uint16_t Skull_Thumb_06_width  = 23;
  constexpr uint16_t Skull_Thumb_06_height = 64;

  constexpr uint24_t Skull_Thumb_07 = 0x00A60E;
  constexpr uint16_t Skull_Thumb_07_width  = 23;
  constexpr uint16_t Skull_Thumb_07_height = 64;

  constexpr uint24_t Skull_Thumb_08 = 0x00A6CA;
  constexpr uint16_t Skull_Thumb_08_width  = 23;
  constexpr uint16_t Skull_Thumb_08_height = 64;

  constexpr uint24_t Skull_Thumb_09 = 0x00A786;
  constexpr uint16_t Skull_Thumb_09_width  = 23;
  constexpr uint16_t Skull_Thumb_09_height = 64;

  constexpr uint24_t Skull_Thumb_10 = 0x00A842;
  constexpr uint16_t Skull_Thumb_10_width  = 23;
  constexpr uint16_t Skull_Thumb_10_height = 64;

  constexpr uint24_t Skull_Thumb_11 = 0x00A8FE;
  constexpr uint16_t Skull_Thumb_11_width  = 23;
  constexpr uint16_t Skull_Thumb_11_height = 64;

  constexpr uint24_t Skull_Thumb_12 = 0x00A9BA;
  constexpr uint16_t Skull_Thumb_12_width  = 23;
  constexpr uint16_t Skull_Thumb_12_height = 64;

  constexpr uint24_t Skull_Thumb_13 = 0x00AA76;
  constexpr uint16_t Skull_Thumb_13_width  = 23;
  constexpr uint16_t Skull_Thumb_13_height = 64;

  constexpr uint24_t Skull_Thumb_14 = 0x00AB32;
  constexpr uint16_t Skull_Thumb_14_width  = 23;
  constexpr uint16_t Skull_Thumb_14_height = 64;

  constexpr uint24_t Skull_Thumb_15 = 0x00ABEE;
  constexpr uint16_t Skull_Thumb_15_width  = 23;
  constexpr uint16_t Skull_Thumb_15_height = 64;

  constexpr uint24_t Skull_Thumb_16 = 0x00ACAA;
  constexpr uint16_t Skull_Thumb_16_width  = 23;
  constexpr uint16_t Skull_Thumb_16_height = 64;

  constexpr uint24_t Skull_Thumb_17 = 0x00AD66;
  constexpr uint16_t Skull_Thumb_17_width  = 23;
  constexpr uint16_t Skull_Thumb_17_height = 64;

  constexpr uint24_t Skull_Thumb_18 = 0x00AE22;
  constexpr uint16_t Skull_Thumb_18_width  = 23;
  constexpr uint16_t Skull_Thumb_18_height = 64;

  constexpr uint24_t Skull_Thumb_19 = 0x00AEDE;
  constexpr uint16_t Skull_Thumb_19_width  = 23;
  constexpr uint16_t Skull_Thumb_19_height = 64;

  constexpr uint24_t Skull_Thumb_Cursor = 0x00AF9A;
  constexpr uint16_t Skull_Thumb_Cursor_width  = 23;
  constexpr uint16_t Skull_Thumb_Cursor_height = 64;

  constexpr uint24_t Skulls = 0x00B056;
  constexpr uint24_t Skulls_Thumb = 0x00B092;
  constexpr uint24_t Zoom_01 = 0x00B0CE;
  constexpr uint16_t Zoom_01_width  = 128;
  constexpr uint16_t Zoom_01_height = 64;

  constexpr uint24_t Zoom_02 = 0x00B8D2;
  constexpr uint16_t Zoom_02_width  = 128;
  constexpr uint16_t Zoom_02_height = 64;

  constexpr uint24_t Zoom_03 = 0x00C0D6;
  constexpr uint16_t Zoom_03_width  = 128;
  constexpr uint16_t Zoom_03_height = 64;

  constexpr uint24_t Zoom_04 = 0x00C8DA;
  constexpr uint16_t Zoom_04_width  = 128;
  constexpr uint16_t Zoom_04_height = 64;

  constexpr uint24_t Zoom_05 = 0x00D0DE;
  constexpr uint16_t Zoom_05_width  = 128;
  constexpr uint16_t Zoom_05_height = 64;

  constexpr uint24_t Zoom_06 = 0x00D8E2;
  constexpr uint16_t Zoom_06_width  = 128;
  constexpr uint16_t Zoom_06_height = 64;

  constexpr uint24_t Zoom_07 = 0x00E0E6;
  constexpr uint16_t Zoom_07_width  = 128;
  constexpr uint16_t Zoom_07_height = 64;

  constexpr uint24_t Zoom_08 = 0x00E8EA;
  constexpr uint16_t Zoom_08_width  = 128;
  constexpr uint16_t Zoom_08_height = 64;

  constexpr uint24_t Zoom_09 = 0x00F0EE;
  constexpr uint16_t Zoom_09_width  = 128;
  constexpr uint16_t Zoom_09_height = 64;

  constexpr uint24_t Zoom_10 = 0x00F8F2;
  constexpr uint16_t Zoom_10_width  = 128;
  constexpr uint16_t Zoom_10_height = 64;

  constexpr uint24_t Zoom_11 = 0x0100F6;
  constexpr uint16_t Zoom_11_width  = 128;
  constexpr uint16_t Zoom_11_height = 64;

  constexpr uint24_t Zoom_12 = 0x0108FA;
  constexpr uint16_t Zoom_12_width  = 128;
  constexpr uint16_t Zoom_12_height = 64;

  constexpr uint24_t Zoom_13 = 0x0110FE;
  constexpr uint16_t Zoom_13_width  = 128;
  constexpr uint16_t Zoom_13_height = 64;

  constexpr uint24_t Zoom_14 = 0x011902;
  constexpr uint16_t Zoom_14_width  = 128;
  constexpr uint16_t Zoom_14_height = 64;

  constexpr uint24_t Zoom_15 = 0x012106;
  constexpr uint16_t Zoom_15_width  = 128;
  constexpr uint16_t Zoom_15_height = 64;

  constexpr uint24_t Zoom_16 = 0x01290A;
  constexpr uint16_t Zoom_16_width  = 128;
  constexpr uint16_t Zoom_16_height = 64;

  constexpr uint24_t Zoom_17 = 0x01310E;
  constexpr uint16_t Zoom_17_width  = 128;
  constexpr uint16_t Zoom_17_height = 64;

  constexpr uint24_t Zoom_18 = 0x013912;
  constexpr uint16_t Zoom_18_width  = 128;
  constexpr uint16_t Zoom_18_height = 64;

  constexpr uint24_t Zoom_19 = 0x014116;
  constexpr uint16_t Zoom_19_width  = 128;
  constexpr uint16_t Zoom_19_height = 64;

  constexpr uint24_t Zoom_20 = 0x01491A;
  constexpr uint16_t Zoom_20_width  = 128;
  constexpr uint16_t Zoom_20_height = 64;

  constexpr uint24_t Zoom_21 = 0x01511E;
  constexpr uint16_t Zoom_21_width  = 128;
  constexpr uint16_t Zoom_21_height = 64;

  constexpr uint24_t Zoom_22 = 0x015922;
  constexpr uint16_t Zoom_22_width  = 128;
  constexpr uint16_t Zoom_22_height = 64;

  constexpr uint24_t Zoom_23 = 0x016126;
  constexpr uint16_t Zoom_23_width  = 128;
  constexpr uint16_t Zoom_23_height = 64;

  constexpr uint24_t Zoom_24 = 0x01692A;
  constexpr uint16_t Zoom_24_width  = 128;
  constexpr uint16_t Zoom_24_height = 64;

  constexpr uint24_t Zoom_25 = 0x01712E;
  constexpr uint16_t Zoom_25_width  = 128;
  constexpr uint16_t Zoom_25_height = 64;

  constexpr uint24_t Zoom_26 = 0x017932;
  constexpr uint16_t Zoom_26_width  = 128;
  constexpr uint16_t Zoom_26_height = 64;

  constexpr uint24_t Zoom_27 = 0x018136;
  constexpr uint16_t Zoom_27_width  = 128;
  constexpr uint16_t Zoom_27_height = 64;

  constexpr uint24_t Zoom_28 = 0x01893A;
  constexpr uint16_t Zoom_28_width  = 128;
  constexpr uint16_t Zoom_28_height = 64;

  constexpr uint24_t Zoom_29 = 0x01913E;
  constexpr uint16_t Zoom_29_width  = 128;
  constexpr uint16_t Zoom_29_height = 64;

  constexpr uint24_t Zoom_30 = 0x019942;
  constexpr uint16_t Zoom_30_width  = 128;
  constexpr uint16_t Zoom_30_height = 64;

  constexpr uint24_t Zoom_31 = 0x01A146;
  constexpr uint16_t Zoom_31_width  = 128;
  constexpr uint16_t Zoom_31_height = 64;

  constexpr uint24_t Zoom_32 = 0x01A94A;
  constexpr uint16_t Zoom_32_width  = 128;
  constexpr uint16_t Zoom_32_height = 64;

  constexpr uint24_t Zoom_33 = 0x01B14E;
  constexpr uint16_t Zoom_33_width  = 128;
  constexpr uint16_t Zoom_33_height = 64;

  constexpr uint24_t Zoom_34 = 0x01B952;
  constexpr uint16_t Zoom_34_width  = 128;
  constexpr uint16_t Zoom_34_height = 64;

  constexpr uint24_t Zoom_35 = 0x01C156;
  constexpr uint16_t Zoom_35_width  = 128;
  constexpr uint16_t Zoom_35_height = 64;

  constexpr uint24_t Zoom_36 = 0x01C95A;
  constexpr uint16_t Zoom_36_width  = 128;
  constexpr uint16_t Zoom_36_height = 64;

  constexpr uint24_t Zoom_37 = 0x01D15E;
  constexpr uint16_t Zoom_37_width  = 128;
  constexpr uint16_t Zoom_37_height = 64;

  constexpr uint24_t Zoom_38 = 0x01D962;
  constexpr uint16_t Zoom_38_width  = 128;
  constexpr uint16_t Zoom_38_height = 64;

  constexpr uint24_t Zoom_39 = 0x01E166;
  constexpr uint16_t Zoom_39_width  = 128;
  constexpr uint16_t Zoom_39_height = 64;

  constexpr uint24_t Zoom_40 = 0x01E96A;
  constexpr uint16_t Zoom_40_width  = 128;
  constexpr uint16_t Zoom_40_height = 64;

  constexpr uint24_t Zoom_41 = 0x01F16E;
  constexpr uint16_t Zoom_41_width  = 128;
  constexpr uint16_t Zoom_41_height = 64;

  constexpr uint24_t Zoom_42 = 0x01F972;
  constexpr uint16_t Zoom_42_width  = 128;
  constexpr uint16_t Zoom_42_height = 64;

  constexpr uint24_t Zoom_43 = 0x020176;
  constexpr uint16_t Zoom_43_width  = 128;
  constexpr uint16_t Zoom_43_height = 64;

  constexpr uint24_t Zoom_44 = 0x02097A;
  constexpr uint16_t Zoom_44_width  = 128;
  constexpr uint16_t Zoom_44_height = 64;

  constexpr uint24_t Zoom_45 = 0x02117E;
  constexpr uint16_t Zoom_45_width  = 128;
  constexpr uint16_t Zoom_45_height = 64;

  constexpr uint24_t Zoom_46 = 0x021982;
  constexpr uint16_t Zoom_46_width  = 128;
  constexpr uint16_t Zoom_46_height = 64;

  constexpr uint24_t Zoom_47 = 0x022186;
  constexpr uint16_t Zoom_47_width  = 128;
  constexpr uint16_t Zoom_47_height = 64;

  constexpr uint24_t Zoom_48 = 0x02298A;
  constexpr uint16_t Zoom_48_width  = 128;
  constexpr uint16_t Zoom_48_height = 64;

  constexpr uint24_t Zoom_49 = 0x022D8E;
  constexpr uint16_t Zoom_49_width  = 128;
  constexpr uint16_t Zoom_49_height = 64;

  constexpr uint24_t Zoom_50 = 0x023192;
  constexpr uint16_t Zoom_50_width  = 128;
  constexpr uint16_t Zoom_50_height = 64;

  constexpr uint24_t Drip_01 = 0x023596;
  constexpr uint16_t Drip_01_width  = 128;
  constexpr uint16_t Drip_01_height = 64;

  constexpr uint24_t Drip_02 = 0x02399A;
  constexpr uint16_t Drip_02_width  = 128;
  constexpr uint16_t Drip_02_height = 64;

  constexpr uint24_t Drip_03 = 0x02419E;
  constexpr uint16_t Drip_03_width  = 128;
  constexpr uint16_t Drip_03_height = 64;

  constexpr uint24_t Drip_04 = 0x0249A2;
  constexpr uint16_t Drip_04_width  = 128;
  constexpr uint16_t Drip_04_height = 64;

  constexpr uint24_t Drip_05 = 0x0251A6;
  constexpr uint16_t Drip_05_width  = 128;
  constexpr uint16_t Drip_05_height = 64;

  constexpr uint24_t Drip_06 = 0x0259AA;
  constexpr uint16_t Drip_06_width  = 128;
  constexpr uint16_t Drip_06_height = 64;

  constexpr uint24_t Drip_07 = 0x0261AE;
  constexpr uint16_t Drip_07_width  = 128;
  constexpr uint16_t Drip_07_height = 64;

  constexpr uint24_t Drip_08 = 0x0269B2;
  constexpr uint16_t Drip_08_width  = 128;
  constexpr uint16_t Drip_08_height = 64;

  constexpr uint24_t Drip_09 = 0x0271B6;
  constexpr uint16_t Drip_09_width  = 128;
  constexpr uint16_t Drip_09_height = 64;

  constexpr uint24_t Drip_10 = 0x0279BA;
  constexpr uint16_t Drip_10_width  = 128;
  constexpr uint16_t Drip_10_height = 64;

  constexpr uint24_t Drip_11 = 0x0281BE;
  constexpr uint16_t Drip_11_width  = 128;
  constexpr uint16_t Drip_11_height = 64;

  constexpr uint24_t Drip_12 = 0x0289C2;
  constexpr uint16_t Drip_12_width  = 128;
  constexpr uint16_t Drip_12_height = 64;

  constexpr uint24_t Drip_13 = 0x0291C6;
  constexpr uint16_t Drip_13_width  = 128;
  constexpr uint16_t Drip_13_height = 64;

  constexpr uint24_t Drip_14 = 0x0299CA;
  constexpr uint16_t Drip_14_width  = 128;
  constexpr uint16_t Drip_14_height = 64;

  constexpr uint24_t Drip_15 = 0x02A1CE;
  constexpr uint16_t Drip_15_width  = 128;
  constexpr uint16_t Drip_15_height = 64;

  constexpr uint24_t Drip_16 = 0x02A9D2;
  constexpr uint16_t Drip_16_width  = 128;
  constexpr uint16_t Drip_16_height = 64;

  constexpr uint24_t Drip_17 = 0x02B1D6;
  constexpr uint16_t Drip_17_width  = 128;
  constexpr uint16_t Drip_17_height = 64;

  constexpr uint24_t Drip_18 = 0x02B9DA;
  constexpr uint16_t Drip_18_width  = 128;
  constexpr uint16_t Drip_18_height = 64;

  constexpr uint24_t Drip_19 = 0x02C1DE;
  constexpr uint16_t Drip_19_width  = 128;
  constexpr uint16_t Drip_19_height = 64;

  constexpr uint24_t Drip_20 = 0x02C9E2;
  constexpr uint16_t Drip_20_width  = 128;
  constexpr uint16_t Drip_20_height = 64;

  constexpr uint24_t Drip_21 = 0x02D1E6;
  constexpr uint16_t Drip_21_width  = 128;
  constexpr uint16_t Drip_21_height = 64;

  constexpr uint24_t Drip_22 = 0x02D9EA;
  constexpr uint16_t Drip_22_width  = 128;
  constexpr uint16_t Drip_22_height = 64;

  constexpr uint24_t Drip_23 = 0x02E1EE;
  constexpr uint16_t Drip_23_width  = 128;
  constexpr uint16_t Drip_23_height = 64;

  constexpr uint24_t Drip_24 = 0x02E9F2;
  constexpr uint16_t Drip_24_width  = 128;
  constexpr uint16_t Drip_24_height = 64;

  constexpr uint24_t Drip_25 = 0x02F1F6;
  constexpr uint16_t Drip_25_width  = 128;
  constexpr uint16_t Drip_25_height = 64;

  constexpr uint24_t Drip_26 = 0x02F9FA;
  constexpr uint16_t Drip_26_width  = 128;
  constexpr uint16_t Drip_26_height = 64;

  constexpr uint24_t Drip_27 = 0x0301FE;
  constexpr uint16_t Drip_27_width  = 128;
  constexpr uint16_t Drip_27_height = 64;

  constexpr uint24_t Drip_28 = 0x030A02;
  constexpr uint16_t Drip_28_width  = 128;
  constexpr uint16_t Drip_28_height = 64;

  constexpr uint24_t Drip_29 = 0x031206;
  constexpr uint16_t Drip_29_width  = 128;
  constexpr uint16_t Drip_29_height = 64;

  constexpr uint24_t Drip_30 = 0x031A0A;
  constexpr uint16_t Drip_30_width  = 128;
  constexpr uint16_t Drip_30_height = 64;

  constexpr uint24_t Drip_31 = 0x03220E;
  constexpr uint16_t Drip_31_width  = 128;
  constexpr uint16_t Drip_31_height = 64;

  constexpr uint24_t Drip_32 = 0x032A12;
  constexpr uint16_t Drip_32_width  = 128;
  constexpr uint16_t Drip_32_height = 64;

  constexpr uint24_t Drip_33 = 0x033216;
  constexpr uint16_t Drip_33_width  = 128;
  constexpr uint16_t Drip_33_height = 64;

  constexpr uint24_t Drip_34 = 0x033A1A;
  constexpr uint16_t Drip_34_width  = 128;
  constexpr uint16_t Drip_34_height = 64;

  constexpr uint24_t Drip_35 = 0x03421E;
  constexpr uint16_t Drip_35_width  = 128;
  constexpr uint16_t Drip_35_height = 64;

  constexpr uint24_t Drip_36 = 0x034A22;
  constexpr uint16_t Drip_36_width  = 128;
  constexpr uint16_t Drip_36_height = 64;

  constexpr uint24_t Drip_37 = 0x035226;
  constexpr uint16_t Drip_37_width  = 128;
  constexpr uint16_t Drip_37_height = 64;

  constexpr uint24_t Drip_38 = 0x035A2A;
  constexpr uint16_t Drip_38_width  = 128;
  constexpr uint16_t Drip_38_height = 64;

  constexpr uint24_t Drip_39 = 0x03622E;
  constexpr uint16_t Drip_39_width  = 128;
  constexpr uint16_t Drip_39_height = 64;

  constexpr uint24_t Drip_40 = 0x036A32;
  constexpr uint16_t Drip_40_width  = 128;
  constexpr uint16_t Drip_40_height = 64;

  constexpr uint24_t Drip_41 = 0x037236;
  constexpr uint16_t Drip_41_width  = 128;
  constexpr uint16_t Drip_41_height = 64;

  constexpr uint24_t Drip_42 = 0x037A3A;
  constexpr uint16_t Drip_42_width  = 128;
  constexpr uint16_t Drip_42_height = 64;

  constexpr uint24_t Drip_43 = 0x03823E;
  constexpr uint16_t Drip_43_width  = 128;
  constexpr uint16_t Drip_43_height = 64;

  constexpr uint24_t Drip_44 = 0x038A42;
  constexpr uint16_t Drip_44_width  = 128;
  constexpr uint16_t Drip_44_height = 64;

  constexpr uint24_t Drip_45 = 0x039246;
  constexpr uint16_t Drip_45_width  = 128;
  constexpr uint16_t Drip_45_height = 64;

  constexpr uint24_t Drip_46 = 0x039A4A;
  constexpr uint16_t Drip_46_width  = 128;
  constexpr uint16_t Drip_46_height = 64;

  constexpr uint24_t Drip_47 = 0x03A24E;
  constexpr uint16_t Drip_47_width  = 128;
  constexpr uint16_t Drip_47_height = 64;

  constexpr uint24_t Drip_48 = 0x03AA52;
  constexpr uint16_t Drip_48_width  = 128;
  constexpr uint16_t Drip_48_height = 64;

  constexpr uint24_t Drip_49 = 0x03B256;
  constexpr uint16_t Drip_49_width  = 128;
  constexpr uint16_t Drip_49_height = 64;

  constexpr uint24_t Drip_50 = 0x03BA5A;
  constexpr uint16_t Drip_50_width  = 128;
  constexpr uint16_t Drip_50_height = 64;

  constexpr uint24_t Drip_51 = 0x03C25E;
  constexpr uint16_t Drip_51_width  = 128;
  constexpr uint16_t Drip_51_height = 64;

  constexpr uint24_t Drip_52 = 0x03CA62;
  constexpr uint16_t Drip_52_width  = 128;
  constexpr uint16_t Drip_52_height = 64;

  constexpr uint24_t Drip_53 = 0x03D266;
  constexpr uint16_t Drip_53_width  = 128;
  constexpr uint16_t Drip_53_height = 64;

  constexpr uint24_t Drip_54 = 0x03DA6A;
  constexpr uint16_t Drip_54_width  = 128;
  constexpr uint16_t Drip_54_height = 64;

  constexpr uint24_t Drip_55 = 0x03E26E;
  constexpr uint16_t Drip_55_width  = 128;
  constexpr uint16_t Drip_55_height = 64;

  constexpr uint24_t Drip_56 = 0x03EA72;
  constexpr uint16_t Drip_56_width  = 128;
  constexpr uint16_t Drip_56_height = 64;

  constexpr uint24_t Drip_57 = 0x03F276;
  constexpr uint16_t Drip_57_width  = 128;
  constexpr uint16_t Drip_57_height = 64;

  constexpr uint24_t Drip_58 = 0x03FA7A;
  constexpr uint16_t Drip_58_width  = 128;
  constexpr uint16_t Drip_58_height = 64;

  constexpr uint24_t Drip_59 = 0x04027E;
  constexpr uint16_t Drip_59_width  = 128;
  constexpr uint16_t Drip_59_height = 64;

  constexpr uint24_t Drip_60 = 0x040A82;
  constexpr uint16_t Drip_60_width  = 128;
  constexpr uint16_t Drip_60_height = 64;

  constexpr uint24_t Zoom = 0x041286;
  constexpr uint24_t Zoom1 = 0x0413D0;
}

