#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = uint32;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfebd;
constexpr uint24_t FX_DATA_BYTES = 78503;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Constants
{
}

namespace Images
{
  constexpr uint24_t Title = 0x000000;
  constexpr uint24_t PPOT = 0x0008A8;
  constexpr uint24_t ClearProgress = 0x0038AA;
  constexpr uint24_t Menu = 0x0039F6;
  constexpr uint24_t Levels_Select = 0x0048F8;
  constexpr uint24_t Levels_Cursor = 0x005F4A;
  constexpr uint24_t Levels_HUD = 0x0060E4;
  constexpr uint24_t Levels_Status = 0x007EB6;
  constexpr uint24_t Levels_Number = 0x00803B;
  constexpr uint24_t Levels_Time = 0x008565;
  constexpr uint24_t Levels_Time_Numbers = 0x0085F1;
  constexpr uint24_t Mini_HUD = 0x008689;
  constexpr uint24_t Numbers_HUD = 0x00874B;
  constexpr uint24_t Numbers_5x3_2D_WB = 0x0090AD;
  constexpr uint24_t Block_Top_01 = 0x009A0F;
  constexpr uint24_t Block_Top_02 = 0x00A2B1;
  constexpr uint24_t Block_Top_03 = 0x00AB53;
  constexpr uint24_t Block_Top_04 = 0x00B3F5;
  constexpr uint24_t Cursor_Top = 0x00BC97;
  constexpr uint24_t Cursor_Left = 0x00BDAD;
  constexpr uint24_t Cursor_Right = 0x00BE87;
  constexpr uint24_t Complete = 0x00BF61;
  constexpr uint24_t GameOver = 0x00C7C1;
  constexpr uint24_t Rotate = 0x00D0C3;
  constexpr uint24_t Size = 0x011B95;
}

